version: '3.9'

services:
  db:
    image: postgres
    container_name: jasper-cloud-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: jc_admin
      POSTGRES_PASSWORD: jaspercloud
      POSTGRES_DB: jasperclouddb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432
