version: '3.9'

services:
  db:
    image: postgres
    container_name: jasper-cloud-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: jc_admin
      POSTGRES_PASSWORD: jaspercloud
      POSTGRES_DB: jasperclouddb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  jasper-cloud-blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: jasper-cloud-blob
    restart: always
    volumes:
      - ./volumes/jasper-cloud-blob/data:/data
    ports:
      - 10000:10000
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
